### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by pakeke-constructor** [Guigui220D/buildoland-3#92]
Hi there!

I was wondering if you had a license on your code for this game.
I think I could learn a lot from extending this current codebase that you have and implementing my own stuff on top of it.

Thanks in advance.

**Comment by Guigui220D** [comment]
Hello! Thanks for your interest in my project

I can't believe I forgot to put a license when I made it public... I'll put one when I have the time, but until now, just don't redistribute it under any other name than, and please mention my username, and that you made changes.

Please note that even though this is my biggest project, I have never been teached how to do things properly so some things are probably done my way, or naïvely (no entity component system, no space partitionning.

I would love to talk about it though, so you can contact me on discord at Ino#7587, or at this email: gderex8@orange.fr.

Have a nice day!

**Comment by pakeke-constructor** [comment]
Thank you very much for the swift response!
Have a good week
